/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VastuGuideRouteImport } from './routes/vastu-guide'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ServicesServiceSlugRouteImport } from './routes/services.$serviceSlug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminSocialRouteImport } from './routes/admin/social'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminLeadsRouteImport } from './routes/admin/leads'
import { Route as AdminCalendarRouteImport } from './routes/admin/calendar'
import { Route as AdminBlogRouteImport } from './routes/admin/blog'

const VastuGuideRoute = VastuGuideRouteImport.update({
  id: '/vastu-guide',
  path: '/vastu-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ServicesServiceSlugRoute = ServicesServiceSlugRouteImport.update({
  id: '/$serviceSlug',
  path: '/$serviceSlug',
  getParentRoute: () => ServicesRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminSocialRoute = AdminSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRouteWithChildren
  '/vastu-guide': typeof VastuGuideRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/social': typeof AdminSocialRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/$serviceSlug': typeof ServicesServiceSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRouteWithChildren
  '/vastu-guide': typeof VastuGuideRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/social': typeof AdminSocialRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/$serviceSlug': typeof ServicesServiceSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRouteWithChildren
  '/vastu-guide': typeof VastuGuideRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/social': typeof AdminSocialRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/$serviceSlug': typeof ServicesServiceSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/contact'
    | '/services'
    | '/vastu-guide'
    | '/admin/blog'
    | '/admin/calendar'
    | '/admin/leads'
    | '/admin/settings'
    | '/admin/social'
    | '/blog/$slug'
    | '/services/$serviceSlug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/services'
    | '/vastu-guide'
    | '/admin/blog'
    | '/admin/calendar'
    | '/admin/leads'
    | '/admin/settings'
    | '/admin/social'
    | '/blog/$slug'
    | '/services/$serviceSlug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/contact'
    | '/services'
    | '/vastu-guide'
    | '/admin/blog'
    | '/admin/calendar'
    | '/admin/leads'
    | '/admin/settings'
    | '/admin/social'
    | '/blog/$slug'
    | '/services/$serviceSlug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  VastuGuideRoute: typeof VastuGuideRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vastu-guide': {
      id: '/vastu-guide'
      path: '/vastu-guide'
      fullPath: '/vastu-guide'
      preLoaderRoute: typeof VastuGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/services/$serviceSlug': {
      id: '/services/$serviceSlug'
      path: '/$serviceSlug'
      fullPath: '/services/$serviceSlug'
      preLoaderRoute: typeof ServicesServiceSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/social': {
      id: '/admin/social'
      path: '/social'
      fullPath: '/admin/social'
      preLoaderRoute: typeof AdminSocialRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBlogRoute: typeof AdminBlogRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSocialRoute: typeof AdminSocialRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlogRoute: AdminBlogRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSocialRoute: AdminSocialRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ServicesRouteChildren {
  ServicesServiceSlugRoute: typeof ServicesServiceSlugRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesServiceSlugRoute: ServicesServiceSlugRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRouteWithChildren,
  VastuGuideRoute: VastuGuideRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
